# Generated by Django 3.2.10 on 2024-10-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20241021_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.URLField(default='/media/img/003044Cwsr1.jpg', max_length=100, verbose_name='网站logo'),
        ),
    ]
