# Generated by Django 3.2.10 on 2024-10-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_site_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='年份')),
            ],
            options={
                'verbose_name': '年份',
                'verbose_name_plural': '年份',
            },
        ),
        migrations.AlterField(
            model_name='site',
            name='bg_cover',
            field=models.URLField(default='/media/img/003044Cwsr1.jpg', max_length=100, verbose_name='背景图片'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.URLField(default='https://jwt1399.top/favicon.png', max_length=100, verbose_name='网站logo'),
        ),
        migrations.AddField(
            model_name='article',
            name='years',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Year', verbose_name='所属年份'),
        ),
    ]
