# Generated by Django 3.2.10 on 2024-11-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20241111_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='years',
        ),
        migrations.AddField(
            model_name='article',
            name='years',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Year', verbose_name='所属年份'),
        ),
    ]
