# Generated by Django 3.2.10 on 2024-11-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20241111_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='years',
        ),
        migrations.AddField(
            model_name='article',
            name='years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.year', verbose_name='所属年份'),
        ),
    ]
