# Generated by Django 3.2.10 on 2024-11-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_year_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='城市名')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='去过的次数')),
            ],
        ),
    ]
