# Generated by Django 3.2.10 on 2024-11-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_article_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=22, null=True, verbose_name='邮箱'),
        ),
    ]
